[build]
  base = "frontend"
  command = "npm ci --install-links=false && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_WORKSPACES = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
