[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../backend/"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10.7.0"
  YARN_FLAGS = "--no-workspace-root"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
