[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "frontend/dist"
  functions = "frontend/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
