[build]
  publish = "./frontend/dist"
  command = "npm install && cd frontend && npm install && npm run build && cd ../backend && npm install && npm run build"
  functions = "./backend/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10.7.0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
